# Copyright (C)
# date: 21-05-2025
# author: cuongwf1711
# email: ruivalien@gmail.com

"""User Constants."""

DEFAULT_LENGTH_REFERENCE_POINT = 5.0
DEFAULT_WIDTH_REFERENCE_POINT = 1.5

MAX_LENGTH_REFERENCE_POINT = 20
MAX_WIDTH_REFERENCE_POINT = 10
MAX_ACTIVITY_FACTOR = 5.0
DEFAULT_ACTIVITY_FACTOR = 1.2
