# Generated by Django 5.2.1 on 2025-05-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myinputimage",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="myinputimage",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
