# Generated by Django 5.2.1 on 2025-05-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="age",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="calorie_limit",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="calorie_limit_period",
            field=models.CharField(
                choices=[("day", "day"), ("week", "week"), ("month", "month")],
                default="day",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="height",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="weight",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
