# Generated by Django 5.2.2 on 2025-06-10 15:07

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0003_userprofile_age_userprofile_calorie_limit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="activity_factor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal(
                    "1.1999999999999999555910790149937383830547332763671875"
                ),
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("5")),
                ],
            ),
        ),
    ]
